### ISSUE TITLE
(node:4) UnhandledPromiseRejectionWarning: ReferenceError: User is not defined 이라고 합니다 무슨 버그인가요?

### ISSUE THREAD

**Issue by filename24** [Ukong0324/Discord-JS-Tutorial#9]

**Comment by Ukong0324** [comment]
2화에 대부분 에러의 의미를 적어왔습니다.

그리고 그런 에러가 발생할 때 어디 명령어이고 해당 오류 스택을 전부 복사하여 코드 박스로 변환하셔서 다시 올려주세요.

**Comment by filename24** [comment]
`2020-06-23T01:37:44.763072+00:00 app[Worker.1]: (node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'money' of undefined
2020-06-23T01:37:44.763119+00:00 app[Worker.1]:     at Object.exports.run (/app/command/ECONOMY/gamle.js:12:29)
2020-06-23T01:37:44.763120+00:00 app[Worker.1]:     at runCommand (/app/index.js:44:22)
2020-06-23T01:37:44.763120+00:00 app[Worker.1]:     at Client.<anonymous> (/app/index.js:55:9)
2020-06-23T01:37:44.763120+00:00 app[Worker.1]:     at Client.emit (events.js:327:22)
2020-06-23T01:37:44.763121+00:00 app[Worker.1]:     at MessageCreateAction.handle (/app/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
2020-06-23T01:37:44.763122+00:00 app[Worker.1]:     at Object.module.exports [as MESSAGE_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
2020-06-23T01:37:44.763122+00:00 app[Worker.1]:     at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
2020-06-23T01:37:44.763123+00:00 app[Worker.1]:     at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
2020-06-23T01:37:44.763123+00:00 app[Worker.1]:     at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
2020-06-23T01:37:44.763124+00:00 app[Worker.1]:     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:125:16)
2020-06-23T01:37:44.763132+00:00 app[Worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1500)
2020-06-23T01:37:44.763134+00:00 app[Worker.1]: (node:4) UnhandledPromiseRejectionWarning: ReferenceError: User is not defined
2020-06-23T01:37:44.763135+00:00 app[Worker.1]:     at Client.<anonymous> (/app/index.js:65:5)
2020-06-23T01:37:44.763135+00:00 app[Worker.1]:     at Client.emit (events.js:327:22)
2020-06-23T01:37:44.763135+00:00 app[Worker.1]:     at MessageCreateAction.handle (/app/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
2020-06-23T01:37:44.763136+00:00 app[Worker.1]:     at Object.module.exports [as MESSAGE_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
2020-06-23T01:37:44.763136+00:00 app[Worker.1]:     at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
2020-06-23T01:37:44.763136+00:00 app[Worker.1]:     at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
2020-06-23T01:37:44.763137+00:00 app[Worker.1]:     at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
2020-06-23T01:37:44.763137+00:00 app[Worker.1]:     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:125:16)
2020-06-23T01:37:44.763137+00:00 app[Worker.1]:     at WebSocket.emit (events.js:315:20)
2020-06-23T01:37:44.763138+00:00 app[Worker.1]:     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:800:20)
2020-06-23T01:37:44.763183+00:00 app[Worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1501)`

**Comment by Ukong0324** [comment]
혹시 json폴더 하나 만드시고 user, server json 생성하셨나요 ?

**Comment by Ukong0324** [comment]
![image](https://user-images.githubusercontent.com/41337427/85379749-17028c00-b577-11ea-80ea-a7463c4853da.png)

**Comment by Ukong0324** [comment]
생성을 안하셨다면 저렇게 생성하시고 안에 {}를 넣어주세요.

**Comment by filename24** [comment]
했는데 오류가 계속떠요
`2020-06-24T07:22:57.345232+00:00 app[Worker.1]: (node:4) UnhandledPromiseRejectionWarning: ReferenceError: User is not defined
2020-06-24T07:22:57.345234+00:00 app[Worker.1]:     at Client.<anonymous> (/app/index.js:65:5)
2020-06-24T07:22:57.345234+00:00 app[Worker.1]:     at Client.emit (events.js:327:22)
2020-06-24T07:22:57.345237+00:00 app[Worker.1]:     at MessageCreateAction.handle (/app/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)`

**Comment by Ukong0324** [comment]
시간 되실때 저에게 DM 주세요.

라이브 쉐어 해드리겠습니다
